# Generated by Django 5.1.3 on 2024-11-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_number',
            field=models.CharField(default='2345', max_length=50),
        ),
    ]
